version: '3'
services:
  demo-service-consul:
    image: consul:latest
    volumes:
    - ./consul/client/demo:/consul/config
    #    - ./consul/client/data/demo:/consul/data
    command: consul agent -data-dir "consul/data" -config-dir "consul/config" -retry-join "consul-server1"
    ports:
    - 9002:8081
    - 8002:21000
    - 10002:8080


  demo-service-envoy:
    image: envoyproxy/envoy-alpine:v1.8.0
    volumes:
    - ./envoy/envoy-dynamic.yml:/etc/envoy.yaml
    command: envoy -c /etc/envoy.yaml --service-cluster demo-sidecar-proxy  --service-node demo-sidecar-proxy
    network_mode: "service:demo-service-consul"
    depends_on:
    - demo-service-consul


  demo-service:
    image: openjdk:11-jre-slim
    volumes:
    - ./java/demo/target/demo-0.0.1-SNAPSHOT.jar:/etc/service.jar
    command: java -jar /etc/service.jar
    network_mode: "service:demo-service-consul"
    depends_on:
    - demo-service-consul


networks:
  default:
    external:
      name: service-mesh-envoy
