version: '2'
services:
  user-service-envoy:
    image: envoyproxy/envoy-alpine:latest
    volumes:
    - ./envoy/static/user-service.yml:/etc/envoy.yaml
    command: envoy -c /etc/envoy.yaml --service-cluster user-service
    ports:
    - 8001:80

  user-service:
    image: openjdk:11-jre-slim
    volumes:
    - ./java/user/target/user-0.0.1-SNAPSHOT.jar:/etc/service.jar
    command: java -jar /etc/service.jar
    network_mode: "service:user-service-envoy"
    depends_on:
    - user-service-envoy

  demo-service-envoy:
    image: envoyproxy/envoy-alpine:latest
    volumes:
    - ./envoy/static/demo-service.yml:/etc/envoy.yaml
    command: envoy -c /etc/envoy.yaml --service-cluster demo-service
    ports:
    - 8002:80

  demo-service:
    image: openjdk:11-jre-slim
    volumes:
    - ./java/demo/target/demo-0.0.1-SNAPSHOT.jar:/etc/service.jar
    command: java -jar /etc/service.jar
    network_mode: "service:demo-service-envoy"
    depends_on:
    - demo-service-envoy
