datacenter = "dc1"
server = true
ui = true
client_addr = "0.0.0.0"
connect {
  enabled = true
  ca_provider = "consul"
  ca_config {
    private_key = <<EOF
-----BEGIN EC PRIVATE KEY-----
MHcCAQEEINjA4hNNbfvGdjgI1NXgd8WSEGTaV8W6Wlm/QAjWVHGCoAoGCCqGSM49
AwEHoUQDQgAEciM16RpJxSvRZWDRlat66ooTdn3p/UMy1F5UN5H8ljyiqsWbXlpK
6l4+VW/bAvtcOhBnNsTSfizBVSuAr5vsoQ==
-----END EC PRIVATE KEY-----
EOF
    root_cert =<<EOF
-----BEGIN CERTIFICATE-----
MIIDbzCCAxSgAwIBAgIRAMTF3hQjKaVDyc8i6P2fL6swCgYIKoZIzj0EAwIwgbkx
CzAJBgNVBAYTAlVTMQswCQYDVQQIEwJDQTEWMBQGA1UEBxMNU2FuIEZyYW5jaXNj
bzEaMBgGA1UECRMRMTAxIFNlY29uZCBTdHJlZXQxDjAMBgNVBBETBTk0MTA1MRcw
FQYDVQQKEw5IYXNoaUNvcnAgSW5jLjFAMD4GA1UEAxM3Q29uc3VsIEFnZW50IENB
IDI2MTU1NjA3Mzk0NTM1MjQ1NDgzMTM4MjI0MzQ4OTg4NDM1MjQyNzAeFw0xOTAz
MjkxNjE0MzJaFw0yNDAzMjcxNjE0MzJaMIG5MQswCQYDVQQGEwJVUzELMAkGA1UE
CBMCQ0ExFjAUBgNVBAcTDVNhbiBGcmFuY2lzY28xGjAYBgNVBAkTETEwMSBTZWNv
bmQgU3RyZWV0MQ4wDAYDVQQREwU5NDEwNTEXMBUGA1UEChMOSGFzaGlDb3JwIElu
Yy4xQDA+BgNVBAMTN0NvbnN1bCBBZ2VudCBDQSAyNjE1NTYwNzM5NDUzNTI0NTQ4
MzEzODIyNDM0ODk4ODQzNTI0MjcwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARy
IzXpGknFK9FlYNGVq3rqihN2fen9QzLUXlQ3kfyWPKKqxZteWkrqXj5Vb9sC+1w6
EGc2xNJ+LMFVK4Cvm+yho4H6MIH3MA4GA1UdDwEB/wQEAwIBhjAPBgNVHRMBAf8E
BTADAQH/MGgGA1UdDgRhBF81Yjo3ODo0YTplMTo1YzpkMzo4MTplMjpmMzo1Nzpj
YTpjYjo0YjowNToxNTo1ZjpiZjpiYjplNDplMDoyMDplYzo4NjoxYTplZTpjZTo0
MDo0Yjo1MDpjMTo1Yzo4MjBqBgNVHSMEYzBhgF81Yjo3ODo0YTplMTo1YzpkMzo4
MTplMjpmMzo1NzpjYTpjYjo0YjowNToxNTo1ZjpiZjpiYjplNDplMDoyMDplYzo4
NjoxYTplZTpjZTo0MDo0Yjo1MDpjMTo1Yzo4MjAKBggqhkjOPQQDAgNJADBGAiEA
iY+WzTZxNjKtmKmIfkbnFQIYaBOgh5f6SbWyd5UHq+sCIQCIMxSaAMcjhf41aqsg
cbhNdWiDIbyw27V38OiehMaEXg==
-----END CERTIFICATE-----
EOF
  }
}
ports {
  grpc = 8502
}

