version: '3'
services:

  consul-server1:
    image: consul:latest
    volumes:
    - ./consul/server/config:/consul/config
#    - ./consul/server/data/server1:/consul/data
    command: consul agent -data-dir "consul/data" -config-dir "consul/config" -bootstrap-expect 3 -retry-join "consul-server1"
    ports:
    - 8500:8500

  consul-server2:
    image: consul:latest
    volumes:
    - ./consul/server/config:/consul/config
#    - ./consul/server/data/server2:/consul/data
    command: consul agent -data-dir "consul/data" -config-dir "consul/config" -bootstrap-expect 3 -retry-join "consul-server1"

  consul-server3:
    image: consul:latest
    volumes:
    - ./consul/server/config:/consul/config
#    - ./consul/server/data/server3:/consul/data
    command: consul agent -data-dir "consul/data" -config-dir "consul/config" -bootstrap-expect 3 -retry-join "consul-server1"

  demo-service-consul:
    image: consul:latest
    volumes:
    - ./consul/client/demo:/consul/config
    #    - ./consul/client/data/demo:/consul/data
    command: consul agent -data-dir "consul/data" -config-dir "consul/config" -retry-join "consul-server1"
    ports:
    - 9002:8081
    - 8002:21000
    - 10002:8080


  demo-service-envoy:
    image: envoyproxy/envoy-alpine:v1.8.0
    volumes:
    - ./envoy/envoy-dynamic.yml:/etc/envoy.yaml
    command: envoy -c /etc/envoy.yaml --service-cluster demo-sidecar-proxy  --service-node demo-sidecar-proxy
    network_mode: "service:demo-service-consul"
    depends_on:
    - demo-service-consul


  demo-service:
    image: openjdk:11-jre-slim
    volumes:
    - ../services/demo/target/demo-0.0.1-SNAPSHOT.jar:/etc/service.jar
    command: java -jar /etc/service.jar
    network_mode: "service:demo-service-consul"
    depends_on:
    - demo-service-consul

  user-service-consul:
    image: consul:latest
    volumes:
    - ./consul/client/user:/consul/config
    #    - ./consul/client/data/user:/consul/data
    command: consul agent -data-dir "consul/data" -config-dir "consul/config" -retry-join "consul-server1"
    ports:
    - 9001:8081
    - 8001:21000
    - 10001:8080


  user-service-envoy:
    image: envoyproxy/envoy-alpine:v1.8.0
    volumes:
    - ./envoy/envoy-dynamic.yml:/etc/envoy.yaml
    command: envoy -c /etc/envoy.yaml --service-cluster user-sidecar-proxy  --service-node user-sidecar-proxy
    network_mode: "service:user-service-consul"
    depends_on:
    - user-service-consul


  user-service:
    image: openjdk:11-jre-slim
    volumes:
    - ../services/user/target/user-0.0.1-SNAPSHOT.jar:/etc/service.jar
    command: java -jar /etc/service.jar
    network_mode: "service:user-service-consul"
    depends_on:
    - user-service-consul
