version: '3'
services:
  user-service-envoy:
    image: envoyproxy/envoy-alpine:latest
    volumes:
    - ./envoy/user-service.yml:/etc/envoy.yaml
    command: envoy -c /etc/envoy.yaml --service-cluster user-service
    ports:
    - 8001:80

  user-service:
    image: maven:3.6.0-jdk-11
    volumes:
    - ../services:/etc/service
    - ~/.m2:/root/.m2
    command: mvn -f /etc/service/user/pom.xml spring-boot:run
    network_mode: "service:user-service-envoy"
    depends_on:
    - user-service-envoy

  demo-service-envoy:
    image: envoyproxy/envoy-alpine:latest
    volumes:
    - ./envoy/demo-service.yml:/etc/envoy.yaml
    command: envoy -c /etc/envoy.yaml --service-cluster demo-service
    ports:
    - 8002:80

  demo-service:
    image: maven:3.6.0-jdk-11
    volumes:
    - ../services:/etc/service
    - ~/.m2:/root/.m2
    command: mvn -f /etc/service/demo/pom.xml spring-boot:run
    network_mode: "service:demo-service-envoy"
    depends_on:
    - demo-service-envoy
