version: '3.5'
services:

  consul-server1:
    image: consul:latest
    volumes:
    - ./server.hcl:/consul/config/server.hcl
    command: consul agent -data-dir "consul/data" -config-dir "consul/config" -bootstrap-expect 3 -retry-join "consul-server1"
    networks:
    - envoy-consul-dns
    ports:
    - 8500:8500

  consul-server2:
    image: consul:latest
    volumes:
    - ./server.hcl:/consul/config/server.hcl
    command: consul agent -data-dir "consul/data" -config-dir "consul/config" -bootstrap-expect 3 -retry-join "consul-server1"
    networks:
    - envoy-consul-dns

  consul-server3:
    image: consul:latest
    volumes:
    - ./server.hcl:/consul/config/server.hcl
    command: consul agent -data-dir "consul/data" -config-dir "consul/config" -bootstrap-expect 3 -retry-join "consul-server1"
    networks:
      - envoy-consul-dns

networks:
  envoy-consul-dns:
    name: envoy-consul-dns
    driver: bridge